name: Teardown
on: [workflow_dispatch]
jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -destroy -no-color
        continue-on-error: true

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve